### ISSUE TITLE
Rounding floats in appearance.2da

### ISSUE THREAD

**Issue by Finaldeath** [Cjreek/Eos-Toolset#14]
Minor issue but some floats in appearance.2da are being truncated/rounded.

eg: WING_TAIL_SCALE column, rows with values like 0.777 are being rounded to 0.78, or 0.632 to 0.63.

Values which are 1.0 (float) are also truncated to 1.

Mainly affects first exports to some kind of source control - not that it should matter a great deal - but comparison with base game files does become more difficult.

Not a major issue probably won't realistically affect a lot but might be an easy one to fix to keep accuracy with data imports.

**Comment by Cjreek** [comment]
Fixed in 0.74
