### ISSUE TITLE
appearances "Sorted" crashes Eos toolset

### ISSUE THREAD

**Issue by Finaldeath** [Cjreek/Eos-Toolset#15]
Using the "sorted" option for appearances seems to crash the toolset. Consistently reproduced with this json file.

Of course just one single entry doesn't crash, but more than one seems to crash (tried with just 2 entries).

[appearances.zip](https://github.com/Cjreek/Eos-Toolset/files/14058170/appearances.zip)

**Comment by Cjreek** [comment]
Fixed in 0.74
