### ISSUE TITLE
Bad data if feat is Duplicated causing crash

### ISSUE THREAD

**Issue by Finaldeath** [Cjreek/Eos-Toolset#17]
Duplicating a feat seems to duplicate it exactly - ie the IDs and UUIDs are the same, so it doesn't appear in the GUI. If you save the files, and try and reopen, it crashes on startup.

I duplicated in the Custom view a feat I'd already Overriden so should be easy to reproduce.

**Comment by Cjreek** [comment]
Fixed in 0.74
