### ISSUE TITLE
Cut feats and classes do not generate constants

### ISSUE THREAD

**Issue by Finaldeath** [Cjreek/Eos-Toolset#18]
Classes like Shou Disciple or feats like Blinding Spittle don't generate constants even if they are manually entered in name.

Not the biggest issue as it were but might be good to have.

**Comment by Finaldeath** [comment]
To add to this there appears to be a epic harper scout ID which clashed when I added a new feat for it (since this one wasn't available to override):

```
int FEAT_EPIC_HARPER_SCOUT     = 981
```

**Comment by Cjreek** [comment]
Fixed/added in 0.74
