### ISSUE TITLE
VFX Impact Effect field is blanked on save

### ISSUE THREAD

**Issue by Finaldeath** [Cjreek/Eos-Toolset#19]
This field is blanked on save:

![image](https://github.com/Cjreek/Eos-Toolset/assets/6137144/604fd0fb-645e-4ab8-8497-3f702177d76f)

Not sure if other fields are affected not found any.

As mentioned previously VFX don't export a script constant yet either but can work around that.

**Comment by Cjreek** [comment]
Fixed in 0.74
