### ISSUE TITLE
UI: cannot create new soundset in Custom

### ISSUE THREAD

**Issue by Finaldeath** [Cjreek/Eos-Toolset#4]
Repo: Right click "Soundsets", here, under Custom:

![image](https://github.com/Cjreek/Eos-Toolset/assets/6137144/df5c07d9-5a1e-470b-b8bb-aa4fbe664d8b)

Click New and you get instead an new "Area Effects" entry added.

**Comment by Cjreek** [comment]
Fixed in 0.73b
