### ISSUE TITLE
Custom Objects don't use Label field

### ISSUE THREAD

**Issue by Finaldeath** [Cjreek/Eos-Toolset#6]
Create a New Object for a custom additional 2da.

Edit the default Label field and it won't update the title of the entry. Looks to be the field doesn't get picked up.

![image](https://github.com/Cjreek/Eos-Toolset/assets/6137144/6a4f9808-0eef-4d8f-85aa-363102ce6015)

Alternatively it's messed up since I also created a field called "Label" I later deleted, which would also be a bug.

**Comment by Cjreek** [comment]
Fixed in 0.73b
